default: &default
  adapter: postgresql
  pool: 5
development:
  <<: *default
  url: "postgresql://localhost/movies_development?encoding=unicode"
test:
  <<: *default
  url: "postgresql://localhost/movies_test?encoding=unicode"
production:
  <<: *default
  url: "postgresql://localhost/movies_production?encoding=unicode"
