# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 104d66ea90ac89d75d0f5bacf4c15aad6309cb270d242c92be12fb79d29dc441e08c62f1e6ce00322e222036c028364a971c99bc91e3205eae0c36589b5021af

test:
  secret_key_base: f4bf721ff4a2d469cb3d91f958bdb44826a298cd810822e11114e1394d284f850c5d1312f2559aaaf2370641d40e3e979c8c50c49f84d764bbeee0903f8db06f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
