default: &default
  adapter: postgresql
  pool: 5
development:
  <<: *default
  url: "postgresql://localhost/projects_development?encoding=unicode"
test:
  <<: *default
  url: "postgresql://localhost/projects_test?encoding=unicode"
production:
  <<: *default
  url: "postgresql://localhost/projects_production?encoding=unicode"
