default: &default
  adapter: postgresql
  pool: 5
development:
  <<: *default
  url: "postgresql://localhost/events_development?encoding=unicode"
test:
  <<: *default
  url: "postgresql://localhost/events_test?encoding=unicode"
production:
  <<: *default
  url: "postgresql://localhost/events_production?encoding=unicode"
