# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 724d7b2a917873deff09d52539e4f7844f7370edab3356d56feea6946eface8ba0a6ba07c6e67acedf2f33fede04d9909b12fd7548fd082b714f4ef51cc6e465

test:
  secret_key_base: 4d7b1dfc182d075df060f8f2206f8bdf5410c00436512a8cae10786f23fc73ebd4ea64eac534360d34ddd785ae3c111a8538f5547ac8b40265bb99908725ca3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
